# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -Dfile.encoding=UTF-8 package --file bankWebApp/pom.xml
    - name: Run Spring tests
      run: mvn -Dfile.encoding=UTF-8 clean test --file bankWebApp/pom.xml
#    - name: Execute Jar File
#      run: sudo kill -9 'sudo lsof -t -i:8080' & sudo java -jar /home/ubuntu/actions-runner/_work/bankWebApp/bankWebApp/bankWebApp/target/bankWebApp-0.0.1-SNAPSHOT.jar &
    - name: Kill Existing Process
      run: |
          echo "kill port 8080"
          echo $(sudo lsof -t -i:8080)
          sudo kill -9 `sudo lsof -t -i:8080`
    - name: Build Maven Jar
      run: |
          cd /home/ubuntu/actions-runner/_work/bankWebApp/bankWebApp/bankWebApp
          sudo mvn clean package
    - name: Execute Jar File
      run: sudo java -jar /home/ubuntu/actions-runner/_work/bankWebApp/bankWebApp/bankWebApp/target/bankWebApp-0.0.1-SNAPSHOT.jar &



    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
